### ISSUE TITLE
Example please 

### ISSUE THREAD

**Issue by levia7han** [rebus-org/Rebus.SimpleInjector#1]
Looking at the tests I have tried to get this working. But no matter how I go at it I always end up with errors saying that the message could not be dispatched to any handlers. 
Could I get an example of this working please?

**Comment by mookid8000** [comment]
I made one [here](https://github.com/rebus-org/RebusSamples/tree/master/SimpleInjector).

Since Rebus resolves handlers by looking for all `IHandleMessages<T>` that are compatible with the current message being handled, it is necessary with SimpleInjector to register the handler type using the `RegisterCollection` method [like this](https://github.com/rebus-org/RebusSamples/blob/master/SimpleInjector/SimpleInjectorTest/Program.cs#L18)

I bet that that was the problem – at least, that's what was MY problem when I created this sample. 😄

**Comment by levia7han** [comment]
That was exactly it. Thank you so much.
